Layout
gostekk/dash pull request #8
Opened 2020-05-23 22:26 UTC by mbrodziak

2020-05-23 23:25 UTC, gostekk requested changes

2020-05-23 23:25 UTC, gostekk commented on app.py
> +app = dash.Dash(__name__, server=server, external_stylesheets=[dbc.themes.BOOTSTRAP])
On bottom of the file you can find external stylesheets. Move it there.

2020-05-23 23:25 UTC, gostekk commented on app.py
> +app = dash.Dash(__name__, server=server, external_stylesheets=[dbc.themes.BOOTSTRAP])
It's on 499 line

2020-05-24 22:22 UTC, mbrodziak commented on app.py
> +app = dash.Dash(__name__, server=server, external_stylesheets=[dbc.themes.BOOTSTRAP])
Then bootstrap doesn't work.

2020-05-25 17:10 UTC, gostekk approved these changes

2020-05-25 17:11 UTC, merged